// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOdCP2oBj-ndcCH1AT4MEBXzLHwjUd1VM',
    appId: '1:558025932981:web:1580709aa180ce35f57efc',
    messagingSenderId: '558025932981',
    projectId: 'payplus-e8557',
    authDomain: 'payplus-e8557.firebaseapp.com',
    storageBucket: 'payplus-e8557.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDQCRAlw9QXVYWtqiIwZ5HzYeC-3UU_s',
    appId: '1:558025932981:android:506e7dccffd51024f57efc',
    messagingSenderId: '558025932981',
    projectId: 'payplus-e8557',
    storageBucket: 'payplus-e8557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHCz0-6pWMyJR0XpcnaMe-dhOMZsXtQQQ',
    appId: '1:558025932981:ios:f808153e1ff0e7b7f57efc',
    messagingSenderId: '558025932981',
    projectId: 'payplus-e8557',
    storageBucket: 'payplus-e8557.firebasestorage.app',
    iosBundleId: 'com.payplus.payPlusMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHCz0-6pWMyJR0XpcnaMe-dhOMZsXtQQQ',
    appId: '1:558025932981:ios:f808153e1ff0e7b7f57efc',
    messagingSenderId: '558025932981',
    projectId: 'payplus-e8557',
    storageBucket: 'payplus-e8557.firebasestorage.app',
    iosBundleId: 'com.payplus.payPlusMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOdCP2oBj-ndcCH1AT4MEBXzLHwjUd1VM',
    appId: '1:558025932981:web:b700ac0a885d0278f57efc',
    messagingSenderId: '558025932981',
    projectId: 'payplus-e8557',
    authDomain: 'payplus-e8557.firebaseapp.com',
    storageBucket: 'payplus-e8557.firebasestorage.app',
  );
}
